stages:
  attention_model:
    cmd: python attention_main.py 2
    metrics:
    - metrics/precision_attention.json:
        cache: false
    - metrics/recall_attention.json:
        cache: false
    - metrics/f1_score_attention.json:
        cache: false
    - metrics/metrics_attention.json:
        cache: false
    outs:
    - trained_models/attention_model/best.pt
  conv_model:
    cmd: python conv_main.py 2
    metrics:
    - metrics/precision_conv.json:
        cache: false
    - metrics/recall_conv.json:
        cache: false
    - metrics/f1_score_conv.json:
        cache: false
    - metrics/metrics_conv.json:
        cache: false
    outs:
    - trained_models/conv_model/best.pt