train:
  epoch: 1
  usecuda: True
  learnrate: 1e-3
  pathsave: "trained_models/attention_model"
  pathsave_conv: "trained_models/conv_model"

attention_model:
  attentionLayer1: 
    in_channels: 1
    out_channels: 16
  attentionLayer2:
    in_channels: 16
    out_channels: 32
  attentionLayer3:
    in_channels: 32
    out_channels: 8
conv_model: 
  convLayer1:
    in_channels: 1
    out_channels: 16
  convLayer2:
    in_channels: 16
    out_channels: 32
  convLayer3:
    in_channels: 32
    out_channels: 8
  